#!/usr/bin/env python3.4

import sys

url = "http://api.naturalreaders.com/v2/tts/?t="+sys.argv[1].replace(" ","%20")+"&r=17&s=1&requesttoken=d741fef70d0214bb9c6cccaea4fc0ab7&recognkey=d3de316a5a135aaa80a98900c4c5e6f7"

import requests,os

req = requests.get(url)
os.system("mkdir /tmp/Lir_TTS/")
file = open('/tmp/Lir_TTS/audio.mp3', 'wb')
for chunk in req.iter_content(100000):
    file.write(chunk)
file.close()
os.system("mpg123 /tmp/Lir_TTS/audio.mp3 &> /dev/null")
