#!/usr/bin/env python3.4

def main():
    import dbus,re,pickle
    bus = dbus.SessionBus()

    players = []
    other = []
    
    for s in bus.list_names():
        if re.match('org.mpris.MediaPlayer2.', s):
            proxy = dbus.SessionBus().get_object(s, '/org/mpris/MediaPlayer2')
            properties_manager = dbus.Interface(proxy, 'org.freedesktop.DBus.Properties')
            metadata = properties_manager.Get('org.mpris.MediaPlayer2.Player', 'Metadata')
            state = properties_manager.Get('org.mpris.MediaPlayer2.Player', 'PlaybackStatus')
            #time = properties_manager.Get('org.mpris.MediaPlayer2.Player','Position')
            #metadata['time'] = time
            metadata['state'] = state
            metadata['player'] = s.split('.')[-1]
            metadata['interface'] = s
            if "mpris:trackid" in metadata:
                metadata['program'] = metadata['mpris:trackid'].split('/')[3]
            data = {}
            for m in metadata:
                if "comment" not in m:
                    if m in ["xesam:artist","xesam:albumArtist","xesam:genre","signature"]:
                        data[str(m)] = str(metadata[m][0])
                    else:
                        data[str(m)] = str(metadata[m])
            #if state == "Playing":
            players.append(data)
            #else:
            #    other.append(data)
    #for s in other:
    #    players.append(s)
        
    with open('/tmp/lir-pickle','wb') as f:
        pickle.dump(players,f)
    print("||pickle||")
    
if __name__ == "__main__":
    main()
